// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: api/dog.proto

package interact

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DogAction int32

const (
	DogAction_UNKNOWN_DOG_ACTION DogAction = 0
	DogAction_POPIS              DogAction = 1
	DogAction_WALK               DogAction = 2
)

// Enum value maps for DogAction.
var (
	DogAction_name = map[int32]string{
		0: "UNKNOWN_DOG_ACTION",
		1: "POPIS",
		2: "WALK",
	}
	DogAction_value = map[string]int32{
		"UNKNOWN_DOG_ACTION": 0,
		"POPIS":              1,
		"WALK":               2,
	}
)

func (x DogAction) Enum() *DogAction {
	p := new(DogAction)
	*p = x
	return p
}

func (x DogAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DogAction) Descriptor() protoreflect.EnumDescriptor {
	return file_api_dog_proto_enumTypes[0].Descriptor()
}

func (DogAction) Type() protoreflect.EnumType {
	return &file_api_dog_proto_enumTypes[0]
}

func (x DogAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DogAction.Descriptor instead.
func (DogAction) EnumDescriptor() ([]byte, []int) {
	return file_api_dog_proto_rawDescGZIP(), []int{0}
}

type SetWalkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action DogAction `protobuf:"varint,1,opt,name=action,proto3,enum=interact.DogAction" json:"action,omitempty"`
}

func (x *SetWalkRequest) Reset() {
	*x = SetWalkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dog_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetWalkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWalkRequest) ProtoMessage() {}

func (x *SetWalkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dog_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWalkRequest.ProtoReflect.Descriptor instead.
func (*SetWalkRequest) Descriptor() ([]byte, []int) {
	return file_api_dog_proto_rawDescGZIP(), []int{0}
}

func (x *SetWalkRequest) GetAction() DogAction {
	if x != nil {
		return x.Action
	}
	return DogAction_UNKNOWN_DOG_ACTION
}

type SetWalkReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *SetWalkReply_Result `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *SetWalkReply) Reset() {
	*x = SetWalkReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dog_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetWalkReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWalkReply) ProtoMessage() {}

func (x *SetWalkReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_dog_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWalkReply.ProtoReflect.Descriptor instead.
func (*SetWalkReply) Descriptor() ([]byte, []int) {
	return file_api_dog_proto_rawDescGZIP(), []int{1}
}

func (x *SetWalkReply) GetResult() *SetWalkReply_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type SetWalkReply_Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Created bool `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
}

func (x *SetWalkReply_Result) Reset() {
	*x = SetWalkReply_Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dog_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetWalkReply_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWalkReply_Result) ProtoMessage() {}

func (x *SetWalkReply_Result) ProtoReflect() protoreflect.Message {
	mi := &file_api_dog_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWalkReply_Result.ProtoReflect.Descriptor instead.
func (*SetWalkReply_Result) Descriptor() ([]byte, []int) {
	return file_api_dog_proto_rawDescGZIP(), []int{1, 0}
}

func (x *SetWalkReply_Result) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

var File_api_dog_proto protoreflect.FileDescriptor

var file_api_dog_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x22, 0x3d, 0x0a, 0x0e, 0x53, 0x65, 0x74,
	0x57, 0x61, 0x6c, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x06, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x44, 0x6f, 0x67, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x69, 0x0a, 0x0c, 0x53, 0x65, 0x74, 0x57,
	0x61, 0x6c, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x35, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x61, 0x63, 0x74, 0x2e, 0x53, 0x65, 0x74, 0x57, 0x61, 0x6c, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x1a,
	0x22, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x2a, 0x38, 0x0a, 0x09, 0x44, 0x6f, 0x67, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x16, 0x0a, 0x12, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x44, 0x4f, 0x47, 0x5f,
	0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x4f, 0x50, 0x49,
	0x53, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x57, 0x41, 0x4c, 0x4b, 0x10, 0x02, 0x32, 0x42, 0x0a,
	0x03, 0x44, 0x6f, 0x67, 0x12, 0x3b, 0x0a, 0x07, 0x53, 0x65, 0x74, 0x57, 0x61, 0x6c, 0x6b, 0x12,
	0x18, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x53, 0x65, 0x74, 0x57, 0x61,
	0x6c, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x61, 0x63, 0x74, 0x2e, 0x53, 0x65, 0x74, 0x57, 0x61, 0x6c, 0x6b, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x64, 0x6f, 0x67, 0x2d, 0x73, 0x6b, 0x79, 0x2f, 0x64, 0x6f, 0x67, 0x5f, 0x62, 0x6f, 0x74, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x61, 0x63, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_dog_proto_rawDescOnce sync.Once
	file_api_dog_proto_rawDescData = file_api_dog_proto_rawDesc
)

func file_api_dog_proto_rawDescGZIP() []byte {
	file_api_dog_proto_rawDescOnce.Do(func() {
		file_api_dog_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_dog_proto_rawDescData)
	})
	return file_api_dog_proto_rawDescData
}

var file_api_dog_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_dog_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_dog_proto_goTypes = []interface{}{
	(DogAction)(0),              // 0: interact.DogAction
	(*SetWalkRequest)(nil),      // 1: interact.SetWalkRequest
	(*SetWalkReply)(nil),        // 2: interact.SetWalkReply
	(*SetWalkReply_Result)(nil), // 3: interact.SetWalkReply.Result
}
var file_api_dog_proto_depIdxs = []int32{
	0, // 0: interact.SetWalkRequest.action:type_name -> interact.DogAction
	3, // 1: interact.SetWalkReply.result:type_name -> interact.SetWalkReply.Result
	1, // 2: interact.Dog.SetWalk:input_type -> interact.SetWalkRequest
	2, // 3: interact.Dog.SetWalk:output_type -> interact.SetWalkReply
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_dog_proto_init() }
func file_api_dog_proto_init() {
	if File_api_dog_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_dog_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetWalkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dog_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetWalkReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dog_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetWalkReply_Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_dog_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_dog_proto_goTypes,
		DependencyIndexes: file_api_dog_proto_depIdxs,
		EnumInfos:         file_api_dog_proto_enumTypes,
		MessageInfos:      file_api_dog_proto_msgTypes,
	}.Build()
	File_api_dog_proto = out.File
	file_api_dog_proto_rawDesc = nil
	file_api_dog_proto_goTypes = nil
	file_api_dog_proto_depIdxs = nil
}
